name: schooly
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.1
  permission_handler: ^5.0.1+1
  progress_indicators: ^0.1.5
  device_info: ^0.4.2+7
  dio: ^3.0.10
  fluttertoast: ^7.0.2
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.0
  url_launcher: 5.5.0
  equatable: ^1.2.4
  webview_flutter: ^0.3.22+1
#  image:
  flutter_bloc: ^6.0.4
  # do ios sim chính chủ (sim vs máy cài ứng dụng) ko gửi sms
  firebase_auth:
    git:
      url: https://github.com/beheobong/flutterfire.git
      path: packages/firebase_auth/firebase_auth
  # multi_image_picker: ^4.6.9: đang bị lỗi trên android ko chọn ảnh được
  multi_image_picker: 4.6.7
  timeago: ^2.0.27
  extended_image: ^1.1.1
  flutter_swiper: ^1.1.6
  onesignal_flutter: ^2.6.1
  google_maps_webservice: ^0.0.18
  uuid: ^2.2.2
  async: ^2.4.2
  html: ^0.14.0+3
  http: ^0.12.2
  flutter_datetime_picker: ^1.4.0
  hive: ^1.4.4
  scroll_to_index: ^1.0.6
  flutter_html: ^1.0.2
  expandable: ^4.1.4
  flutter_rounded_progress_bar: ^0.1.2
  flutter_slidable: ^0.5.7
  fijkplayer: ^0.8.7
  # flutter_filereader: ^2.1.0
  # flutter_filereader: xóa bỏ android do lib của TQ
  flutter_filereader:
    git: https://github.com/beheobong/flutter_filereader.git
  flutter_cupertino_date_picker: ^1.0.26+2
  fl_chart: ^0.11.0
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: master
  flutter_page_indicator: ^0.0.3
  smooth_star_rating: ^1.1.1
  common_utils: ^1.2.1
  positioned_tap_detector: ^1.0.3
  transparent_image: ^1.0.0
  file_picker: ^1.13.3
  flutter_date_pickers: ^0.1.7
  flutter_full_pdf_viewer: ^1.0.6
  share: 0.6.4+5
  android_intent: ^0.3.7+3
  socket_io_client: ^0.9.11
  open_file: ^3.0.1
  flutter_webview_plugin: ^0.3.11
  geolocator: ^5.3.2+2
  flutter_screenutil: ^2.3.1
  uni_links: ^0.4.0
  receive_sharing_intent: ^1.4.1
  share_extend: ^1.1.9
  flutter_video_compress: ^0.3.7+8
  flutter_native_image: ^0.0.5+2
  location: ^3.0.2
  flutter_web_auth: ^0.2.4
  archive: ^2.0.13
  intl: ^0.16.1
  keyboard_dismisser: ^1.0.2

dev_dependencies:
  hive_generator: 
  build_runner: 1.10.1
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons_tab/
    - assets/fonts/
    - assets/json/
    - assets/account/
    - assets/icons_ios/
    - assets/bankicon/

  fonts:
    - family: SanFranciscoText
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
